@url=http://localhost:3000/admin/api
@json=Content-Type: application/json

###
get {{url}}/

###
get {{url}}/bangumis

###
delete {{url}}/removeCsl

###
get {{url}}/bangumis/3

###
post {{url}}/bangumis
{{json}}

{
    "name": "33333333333333333333",
    "type_id": 1,
    "imgSrc": "dawdawdw",
    "episodes": "12",
    "status": 2,
    "style": "战斗、热血",
    "initials": "D",
    "playtime": "2019-10-07",
    "quarter":"10",
    "years": "2019",
    "actors":"户松遥、松冈祯丞",
    "summary":"虚拟游戏战斗番"
}

###
post {{url}}/users/codePhoneLogin
{{json}}

{
    "phone": "13980769536",
    "code": "6893"
}